# Basics

In [2]:
import numpy as  np

In [35]:
arr1=np.array([1,2,3,4,5,6])

print(arr1.shape)
type(arr1)

(6,)


numpy.ndarray

In [36]:
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr2.shape)
type(arr2)

(3, 2)


numpy.ndarray

In [42]:
arr1.shape=(3,2) # shape changing
print(arr1)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
arr3=np.array([1,2,3,4,5,6])

In [49]:
arr4=np.reshape(arr3,(3,2)) # nto changing orginal shape of array

In [47]:
print(arr3)

[1 2 3 4 5 6]


In [50]:
print(arr4)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
arr =np.array(input().split(' '))


4 5 3 4 5


# CODE hackerrank numpy shape

In [5]:
import numpy

arr= numpy.array(input().split(' '),int)
print(numpy.reshape(arr,(3,3)))


4 5 6 2 4 2 5 1 3
[[4 5 6]
 [2 4 2]
 [5 1 3]]
