# Basics

In [1]:
import numpy as np

In [6]:
my_array = np.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])
print(my_array.shape)
print(my_array)

(4, 2)
[[2 5]
 [3 7]
 [1 3]
 [4 0]]


In [7]:
print(np.min(my_array,axis=0)) # cheack rowise and found the most minimum value of the colum
print(np.min(my_array,axis=1)) # check column wise and find the minimum value of each row
print(np.min(my_array,axis=None))
print(np.min(my_array))

[1 0]
[2 3 1 0]
0
0


In [9]:
print(np.max(my_array,axis=0)) # cheack rowise and found the most minimum value of the colum
print(np.max(my_array,axis=1)) # check column wise and find the minimum value of each row
print(np.max(my_array,axis=None))
print(np.max(my_array))

[4 7]
[5 7 3 4]
7
7


In [ ]:
import numpy as np
N,M=map(int,input().split(" "))
arr=np.array([input().strip().split() for i in range(N)],int)
print(np.max(np.max(arr,axis=1)))