# Basics

In [1]:
import numpy as np

In [9]:
a=np.array([1,2,3,4],int)
b=np.array([5,6,7,8],int)

print(a+b)
print(np.add(a,b))
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.floor_divide(a,b))
print(np.mod(a,b))
print(np.power(b,a))

[ 6  8 10 12]
[ 6  8 10 12]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[1 2 3 4]
[   5   36  343 4096]


# hackerRank solution

In [12]:
import numpy as np
N,M=map(int,input().split(" "))
arr_1=np.array([input().strip().split() for i in range(N)],int)
arr_2=np.array([input().strip().split() for i in range(N)],int)
print(np.add(arr_1,arr_2))
print(np.subtract(arr_1,arr_2))
print(np.multiply(arr_1,arr_2))
print(np.floor_divide(arr_1,arr_2))
print(np.mod(arr_1,arr_2))
print(np.power(arr_1,arr_2))




1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
